"""Build quoter estimate curves from Insurance Toolkits check quotes (data/toolkits-checks.json).
Writes public/hp-est.js: per carrier, per sex, per class -> [[age, monthly at $10k], ...] plus fee and multipliers.
Usage: python3 -I scripts/build_est.py [--holdout]   (--holdout prints leave-one-out error instead)"""
import json, math, sys
D = json.load(open("data/toolkits-checks.json"))
# plan name -> (desk carrier, class)
MAP = {
 ("Aetna","Protection Series Preferred"):("Aetna","pref"),
 ("Aetna (CVS/Accendo)","Accendo Standard"):("Aetna","std"),
 ("Foresters","PlanRight Preferred"):("Foresters","pref"),
 ("Foresters","PlanRight Standard"):("Foresters","std"),
 ("Corebridge","SimpliNow Legacy Max"):("Corebridge","pref"),
 ("Ethos","Level"):("Ethos","pref"),
 ("American Home Life","Patriot Series Preferred"):("American Home Life","pref"),
 ("American Home Life","Patriot Series Standard"):("American Home Life","std"),
 ("Fidelity Life","Level"):("Fidelity Life","pref"),
}
# monthly policy fee, from $10k vs $20k quotes for male 60 (Foresters / AHL not measured: assumed $3.00)
FEE = {"Corebridge":3.20,"Aetna":3.34,"Ethos":6.00,"Fidelity Life":7.40,"Foresters":3.00,"American Home Life":3.00}
pts = {}
for q in D["quotes"]:
    if q["health"]!="clean" or q["tobacco"] or q["face"]!=10000: continue
    for r in q["rows"]:
        k = MAP.get((r["carrier"],r["plan"]))
        if not k: continue
        pts.setdefault(k[0],{}).setdefault(q["sex"],{}).setdefault(k[1],{})[q["age"]] = r["monthly"]
# tobacco: male 60 $20k smoker vs nonsmoker, per-unit ratio (only carriers seen in both)
def tob():
    ns = {}; sm = {}
    for q in D["quotes"]:
        if q["face"]!=20000: continue
        for r in q["rows"]:
            k = MAP.get((r["carrier"],r["plan"]))
            if k: (sm if q["tobacco"] else ns)[k] = r["monthly"]
    out = {}
    for k in sm:
        if k in ns: out[k[0]] = round((sm[k]-FEE[k[0]])/(ns[k]-FEE[k[0]]),3)
    return out
TOB = tob()

def curve(c, sex, cls, P=None):
    P = P or pts
    d = P.get(c,{}).get(sex,{}).get(cls)
    return sorted(d.items()) if d else []

def est(c, sex, cls, age, P=None):
    """monthly at $10k; falls back to other sex with a 5-year age setback, then pref x std ratio."""
    P = P or pts
    pairs = curve(c,sex,cls,P)
    shift = 0
    if len(pairs) < 2:
        o = "F" if sex=="M" else "M"; op = curve(c,o,cls,P)
        if len(op) >= 2: pairs, shift = op, (-5 if sex=="F" else 5)
    if len(pairs) < 2:
        if cls=="std":
            p = est(c,sex,"pref",age,P)
            return None if p is None else FEE[c] + (p-FEE[c])*1.3
        return None
    a = age + shift; f = FEE[c]
    xs = [x for x,_ in pairs]; ys = [math.log(y-f) for _,y in pairs]
    if a <= xs[0]: i = 1
    elif a >= xs[-1]: i = len(xs)-1
    else: i = next(j for j in range(1,len(xs)) if a <= xs[j])
    t = (a-xs[i-1])/(xs[i]-xs[i-1])
    return f + math.exp(ys[i-1] + t*(ys[i]-ys[i-1]))

if "--holdout" in sys.argv:
    errs = []
    for c,bys in pts.items():
        for sex,byc in bys.items():
            for cls,ages in byc.items():
                for a,v in ages.items():
                    if a in (min(ages),max(ages)) and len(ages)>2: pass
                    P = json.loads(json.dumps({k:{s:{cl:{str(x):y for x,y in aa.items()} for cl,aa in bc.items()} for s,bc in bs.items()} for k,bs in pts.items()}))
                    P = {k:{s:{cl:{int(x):y for x,y in aa.items()} for cl,aa in bc.items()} for s,bc in bs.items()} for k,bs in P.items()}
                    del P[c][sex][cls][a]
                    e = est(c,sex,cls,a,P)
                    if e: errs.append((abs(e-v), (e-v)/v*100, c, sex, cls, a, v, round(e,2)))
    errs.sort(reverse=True)
    import statistics
    print("held-out checks:", len(errs))
    print("median miss $%.2f (%.1f%%), 90th pct $%.2f" % (statistics.median(e[0] for e in errs), statistics.median(abs(e[1]) for e in errs), sorted(e[0] for e in errs)[int(len(errs)*.9)]))
    print("within $3:", sum(e[0]<=3 for e in errs), " within 5%:", sum(abs(e[1])<=5 for e in errs))
    for e in errs[:8]: print("  worst: %s %s %s age %d actual $%.2f est $%.2f (%+.1f%%)" % (e[2],e[3],e[4],e[5],e[6],e[7],e[1]))
    sys.exit()

out = {"asOf":"Oct 2026","source":"Insurance Toolkits check quotes (Texas, bank draft)","fee":FEE,"tob":TOB,
       "curves":{c:{s:{cl:sorted([[a,v] for a,v in ag.items()]) for cl,ag in bc.items()} for s,bc in bs.items()} for c,bs in pts.items()}}
open("public/hp-est.js","w").write("/* Generated by scripts/build_est.py from data/toolkits-checks.json. Monthly premium at $10,000, clean, no nicotine, TX. Do not edit by hand. */\nwindow.HP_EST = "+json.dumps(out)+";\n")
print("carriers:", {c:{s:{cl:len(a) for cl,a in bc.items()} for s,bc in bs.items()} for c,bs in pts.items()}); print("tobacco:", TOB)

# ---------- Ethos term (data/ethos-term.csv) ----------
def ethos_term():
    rows = [l.strip().split(",") for l in open("data/ethos-term.csv") if l.strip() and not l.startswith("#")]
    grid, face = {}, {}
    for s,age,t,fk,tob,mn,mx in rows:
        if not mn or mn == mx: continue
        age, t, fk, mn, mx = int(age), int(t), int(fk), float(mn), float(mx)
        if fk == 250: grid.setdefault(s+tob,{}).setdefault(str(t),[]).append([age,mn,mx])
        else: face.setdefault(s,{}).setdefault(str(age),{})[str(fk)] = [mn,mx]
    for s,byage in face.items():
        for age,d in byage.items():
            base = next(r for r in grid[s+"0"]["20"] if r[0]==int(age))
            for fk,(mn,mx) in d.items(): d[fk] = [round(mn/base[1],4), round(mx/base[2],4)]
    for g in grid.values():
        for t in g: g[t].sort()
    return {"asOf":"Oct 2026","source":"ethos.com quick estimator (TX)","grid":grid,"face":face}
if __name__ == "__main__" and "--holdout" not in sys.argv:
    s = open("public/hp-est.js").read().rstrip().rstrip(";")
    obj = json.loads(s.split("window.HP_EST = ",1)[1]); obj["ethosTerm"] = ethos_term()
    open("public/hp-est.js","w").write(s.split("window.HP_EST = ",1)[0]+"window.HP_EST = "+json.dumps(obj)+";\n")
    print("ethos term:", {k:{t:len(v) for t,v in g.items()} for k,g in obj["ethosTerm"]["grid"].items()}, obj["ethosTerm"]["face"])
